# Generated by Django 4.0.4 on 2022-05-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productapp',
            name='slug',
            field=models.SlugField(default=' ', max_length=128),
            preserve_default=False,
        ),
    ]
