# Generated by Django 4.0.4 on 2022-05-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='produit',
            new_name='product',
        ),
    ]
